### ISSUE TITLE
BigDL docker is not ready for users' out-of-box usage - No module named 'bigdl'

### ISSUE THREAD

**Issue by TheaperDeng** [intel/ipex-llm#4681]
https://github.com/intel-analytics/BigDL/tree/main/docker/bigdl

- Currently, bigdl docker is not available for users to directly enjoy the bigdl environment
  
  ```bash
  (bigdl) root@cpx-3:/opt/work# python
  Python 3.7.13 (default, Mar 29 2022, 02:18:16)
  [GCC 7.5.0] :: Anaconda, Inc. on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import bigdl
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ModuleNotFoundError: No module named 'bigdl'
  ```

This is mainly because bigdl docker does not unzip the python source code 

```bash
(bigdl) root@cpx-3:/opt/work# ls
bigdl-2.1.0-SNAPSHOT  spark-2.4.6  start-notebook.sh
(bigdl) root@cpx-3:/opt/work# cd bigdl-2.1.0-SNAPSHOT/
(bigdl) root@cpx-3:/opt/work/bigdl-2.1.0-SNAPSHOT# ls
apps  bin  conf  examples  jars  python
(bigdl) root@cpx-3:/opt/work/bigdl-2.1.0-SNAPSHOT# cd python/
(bigdl) root@cpx-3:/opt/work/bigdl-2.1.0-SNAPSHOT/python# ls
bigdl-dllib-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip     bigdl-serving-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip
bigdl-friesian-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip  bigdl-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip
bigdl-orca-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip

```

- bigdl-nano is not fetched to this docker

**Comment by glorysdj** [comment]
not sure why this PR removed all the bigdl settings for jupyter.
https://github.com/intel-analytics/BigDL/pull/3938
@Le-Zheng

**Comment by Le-Zheng** [comment]
> 

This is becasue pythonpath was not setted in bigdl docker `PYTHONPATH=bigdl-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip`, which will be fixed in https://github.com/intel-analytics/BigDL/pull/4690.
And pls add nano source code in https://github.com/intel-analytics/BigDL/blob/main/python/python-zip.xml

**Comment by Le-Zheng** [comment]
> not sure why this PR removed all the bigdl settings for jupyter. #3938 @Le-Zheng

We intended to use `jupyter notebook --notebook-dir=/opt/work/bigdl-2.1.0-SNAPSHOT/apps --ip=0.0.0.0 --port=12345 --no-browser --NotebookApp.token=1234qwer --allow-root` to call init_orca_context to start spark for different modes. @hkvision  in https://github.com/intel-analytics/BigDL/issues/3875

Shall we move above to a `start-notebook-without-spark.sh` to start a jupyter notebook in use init_orca_context(cluster_mode="local"/"k8s"/"yarn")
And reset the original start-notebook.sh for spark-submit as default?

**Comment by hkvision** [comment]
> is PR removed all the bigdl settings for jupyter.
> #3938
> @Le-Zheng

This PR just removes the settings of launch spark-submit and the recommended way is to call init_orca_context in the code. It doesn't remove any bigdl installation in the docker image.

**Comment by Le-Zheng** [comment]
There are 2 options to install bigdl in BigDL Docker.
Option1. currently, we use bigdl-assmbly which contains *python.zip and jars. And we need to fix this image by setting `BIGDL_CLASSPATH=${BIGDL_HOME}/jars/*` and `PYTHONPATH=${BIGDL_HOME}/python/bigdl-spark_${SPARK_VERSION}-${BIGDL_VERSION}-python-api.zip` in image.
Option2. only `pip install bigdl` in image. We need to replace bigdl-assmbly with `pip install bigdl`, and remove `spark_home` since pyspark will be installed. And this image will not support scala examples.
Which one do we prefer?  @hkvision @glorysdj

**Comment by Le-Zheng** [comment]
> https://github.com/intel-analytics/BigDL/tree/main/docker/bigdl
> 
> * Currently, bigdl docker is not available for users to directly enjoy the bigdl environment
>   ```shell
>   (bigdl) root@cpx-3:/opt/work# python
>   Python 3.7.13 (default, Mar 29 2022, 02:18:16)
>   [GCC 7.5.0] :: Anaconda, Inc. on linux
>   Type "help", "copyright", "credits" or "license" for more information.
>   >>> import bigdl
>   Traceback (most recent call last):
>     File "<stdin>", line 1, in <module>
>   ModuleNotFoundError: No module named 'bigdl'
>   ```
> 
> This is mainly because bigdl docker does not unzip the python source code
> 
> ```shell
> (bigdl) root@cpx-3:/opt/work# ls
> bigdl-2.1.0-SNAPSHOT  spark-2.4.6  start-notebook.sh
> (bigdl) root@cpx-3:/opt/work# cd bigdl-2.1.0-SNAPSHOT/
> (bigdl) root@cpx-3:/opt/work/bigdl-2.1.0-SNAPSHOT# ls
> apps  bin  conf  examples  jars  python
> (bigdl) root@cpx-3:/opt/work/bigdl-2.1.0-SNAPSHOT# cd python/
> (bigdl) root@cpx-3:/opt/work/bigdl-2.1.0-SNAPSHOT/python# ls
> bigdl-dllib-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip     bigdl-serving-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip
> bigdl-friesian-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip  bigdl-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip
> bigdl-orca-spark_2.4.6-2.1.0-SNAPSHOT-python-api.zip
> ```
> 
> * bigdl-nano is not fetched to this docker

The issue of "no module named 'bigdl'" has been fixed in the latest bigdl docker image `sudo docker pull intelanalytics/bigdl:2.1.0-SNAPSHOT`
